class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/home/lzw/LEF/Github_load/DGTrack'
        self.tensorboard_dir = '/home/lzw/LEF/Github_load/DGTrack/tensorboard'
        self.pretrained_networks = '/home/lzw/LEF/Github_load/DGTrack/pretrained_networks'
        self.lasot_dir = '/home/lzw/LEF/Github_load/DGTrack/data/lasot'
        self.got10k_dir = '/home/lzw/LEF/Github_load/DGTrack/data/got10k/train'
        self.got10k_val_dir = '/home/lzw/LEF/Github_load/DGTrack/data/got10k/val'
        self.lasot_lmdb_dir = '/home/lzw/LEF/Github_load/DGTrack/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/home/lzw/LEF/Github_load/DGTrack/data/got10k_lmdb'
        self.trackingnet_dir = '/home/lzw/LEF/Github_load/DGTrack/data/trackingnet'
        self.trackingnet_lmdb_dir = '/home/lzw/LEF/Github_load/DGTrack/data/trackingnet_lmdb'
        self.coco_dir = '/home/lzw/LEF/Github_load/DGTrack/data/coco'
        self.coco_lmdb_dir = '/home/lzw/LEF/Github_load/DGTrack/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/home/lzw/LEF/Github_load/DGTrack/data/vid'
        self.imagenet_lmdb_dir = '/home/lzw/LEF/Github_load/DGTrack/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
